language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
# command to run tests
install:
  - pip install pytest pytest-cov pytest-pep8
  - pip install coveralls
script:
  - py.test --cov=pysllo -v --pep8
after_success: coveralls